### ISSUE TITLE
vote() function fails at steem.broadcast.vote()

### ISSUE THREAD

**Issue by jl2035** [theserranos/SteemAutoVoter#1]
AssertionError: Expected version 128, instead got 149
    at Function.value (https://cdn.steemjs.com/lib/latest/steem.min.js:11:9017)
    at p (https://cdn.steemjs.com/lib/latest/steem.min.js:11:12018)
    at Function.value (https://cdn.steemjs.com/lib/latest/steem.min.js:11:11432)
    at Function.value (https://cdn.steemjs.com/lib/latest/steem.min.js:11:11275)
    at Object.p.signTransaction (https://cdn.steemjs.com/lib/latest/steem.min.js:4:28636)
    at https://cdn.steemjs.com/lib/latest/steem.min.js:12:682
From previous event:
    at Object.w.send (https://cdn.steemjs.com/lib/latest/steem.min.js:12:553)
    at Object.w.(anonymous function) [as voteWith] (https://cdn.steemjs.com/lib/latest/steem.min.js:12:1584)
    at Object.w.(anonymous function) [as vote] (https://cdn.steemjs.com/lib/latest/steem.min.js:12:2053)
    at vote (SteemAutoVoter/functions.js:44:18)
    at Steem/SteemAutoVoter/functions.js:64:4

**Comment by Devba** [comment]
Should work fine on new version
Could you check it out again?

**Comment by Devba** [comment]
Should work fine now

**Comment by jl2035** [comment]
I checked today. Still the same error on Chromium: Expected version 128, instead got 149

Also not working in Firefox.

**Comment by Devba** [comment]
You get that error because you are not using the right Private posting key 
Could you check you are using the right key?

**Comment by jl2035** [comment]
Yes my posting key is correct. I somehow got over that error. My current problem is:

Uncaught TypeError: Cannot read property 'payload' of undefined

**Comment by Devba** [comment]
should work fine now
